### ISSUE TITLE
Can we utilize any Watson services?

### ISSUE THREAD

**Issue by sdeastcott** [sdeastcott/Grouplytics#21]

**Comment by marcushill** [comment]
You almost certainly could. With a little data massaging, you could (probably) put each user's message history through the Personality and Sentiment services (Personality Insights and Sentiment Analysis I think, but I'm going from memory). 

That's probably the most obvious use, but you might also be able to use the Content analysis tools (Concept Insights?) to gain some kind of idea of each group is talking about overall (and you could break it up into timed chunks to do trends) and you might find some of the Alchemy APIs to be helpful. I mention Alchemy separately because it had (slightly) separate documentation last time I looked it.
